language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules/
addons:
  sonarcloud:
    organization: "cpibm"
script:
  - npm run lint
  - npm run test:coverage
  - sonar-scanner
notifications:
  slack: pricing-devops-data:ySHtvUhPj027gYheZBAMWKA4